export type RoleDefinition = {
  name: string;
  rate: number;
};

/**
 * Canonical delivery role catalog for the Estimates workflow.
 *
 * This list is used by:
 * - Runtime defaults via `ensureDefaultRolesSeeded`
 * - Prisma seed data in `prisma/seedData.ts`
 *
 * IDs are generated by the database; callers should treat `name` as the
 * stable, human-visible identifier and look up roles by ID at runtime.
 */
export const DEFAULT_ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    name: "Principal Consultant",
    rate: 250.0,
  },
  {
    name: "Senior Product Manager",
    rate: 185.0,
  },
  {
    name: "Senior Software Engineer",
    rate: 165.0,
  },
  {
    name: "UI/UX Designer",
    rate: 145.0,
  },
  {
    name: "QA Engineer",
    rate: 110.0,
  },
  {
    name: "DevOps Engineer",
    rate: 175.0,
  },
  {
    name: "Solutions Architect",
    rate: 200.0,
  },
];


